name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@reaccord/cli'
          - package: 'reaccord'
          - package: '@reaccord/router'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: ${{ matrix.package }}
        run: |
          pnpm ci
          ./node_modules/.bin/turbo run build --scope="${{ matrix.package }}" --no-deps --include-dependencies