name: Publish dev
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'djobbo'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: reaccord
            folder: packages/reaccord
          - name: '@reaccord/router'
            folder: packages/router
          - name: '@reaccord/canvas'
            folder: packages/canvas
          - name: '@reaccord/chalk'
            folder: packages/chalk
          - name: create-reaccord-app
            folder: packages/create-reaccord-app
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Publish to npm
        run: |
          bun run ci:install
          npm set //registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN
          bun run ./scripts/publish-dev.js ${{ matrix.name }} ${{ matrix.folder }}
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
