name: Publish dev
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'djobbo'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: reaccord
            package: reaccord
            folder: reaccord
          - name: '@reaccord/router'
            package: router
            folder: '@reaccord/router'
          - name: '@reaccord/canvas'
            package: canvas
            folder: '@reaccord/canvas'
          - name: '@reaccord/chalk'
            package: chalk
            folder: '@reaccord/chalk'
          - name: create-reaccord-app
            package: create-reaccord-app
            folder: create-reaccord-app
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Publish to npm
        run: |
          bun run ci:install
          bun run ./scripts/publish-dev.js ${{ matrix.package }} ${{ matrix.folder }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
